# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.55/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - dZd3c7J
  content:
    - component: Text
      name: text
      props:
        value: LISTE ET CRUD DES TÂCHES
        variant: h3
      layout:
        columnSize: 1.681241184767278
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
        gap: 3
      children:
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1.1976400279717458
          children:
            - component: DataGrid
              name: gridTache
              layout:
                columnSize: 1
              props:
                rows:
                  $$jsExpression: "switchFini.checked ? allListe.rows : listeall.rows"
                columns:
                  - field: id
                    type: number
                    width: 50
                  - field: utilisateur_id
                    type: number
                    width: 155
                  - field: titre
                    type: string
                  - field: description
                    type: string
                  - field: date_debut
                    type: dateTime
                  - field: date_echeance
                    type: dateTime
                  - field: complete
                    type: json
                  - field: tache_id
                    type: number
                density: standard
            - component: Checkbox
              name: switchFini
              props:
                mode: switch
                label: Fini
        - component: DataGrid
          name: gridSousTache
          layout:
            columnSize: 0.8023599720282542
            height: 244
          props:
            rows:
              $$jsExpression: listeSous.rows
            columns:
              - field: id
                type: number
                width: 50
              - field: tache_id
                type: number
              - field: titre
                type: string
                width: 135
              - field: complete
                type: json
            loading: false
    - component: PageRow
      name: pageRow2
      props:
        justifyContent: start
      children:
        - component: Text
          name: text1
          props:
            value: "ID :"
            variant: h6
          layout:
            columnSize: 0.22303943579481667
        - component: Text
          name: text2
          props:
            value:
              $$jsExpression: gridTache.selection.id
          layout:
            columnSize: 0.22303147838498322
        - component: Spacer
          name: spacer1
          layout:
            columnSize: 2.5539290858202
    - component: PageRow
      name: pageRow3
      props:
        justifyContent: start
      children:
        - component: Text
          name: text5
          props:
            value: "CRÉATION:"
            variant: h6
        - component: Text
          name: text3
          props:
            value:
              $$jsExpression: gridTache.selection.date_debut
        - component: Text
          name: text4
          props:
            value: FIN
            variant: h6
        - component: Text
          name: text6
          props:
            value:
              $$jsExpression: gridTache.selection.date_echeance
    - component: PageRow
      name: pageRow1
      props:
        justifyContent: start
      children:
        - component: Text
          name: text7
          props:
            value: "TITRE:"
            variant: h6
        - component: Text
          name: text8
          props:
            value:
              $$jsExpression: gridTache.selection.titre
    - component: PageRow
      name: pageRow5
      props:
        justifyContent: start
      children:
        - component: Text
          name: text9
          props:
            value: "DESCRIPTION:"
            variant: h6
        - component: Text
          name: text10
          props:
            value:
              $$jsExpression: gridTache.selection.description
    - component: PageRow
      name: pageRow4
      props:
        justifyContent: start
      children:
        - component: Button
          name: button
          props:
            content: SUPPRIMER TÂCHE
            onClick:
              $$jsExpressionAction: action.call();action.fetch()
        - component: Button
          name: button1
          props:
            content: COMPLETER TÂCHE
        - component: Button
          name: button2
          props:
            content: SUPPRIMER          SOUS-TÂCHE
        - component: Button
          name: button3
          props:
            content: COMPLETER SOUS-TÂCHE
            onClick:
              $$jsExpressionAction: statueSousTache.fetch()
    - component: Spacer
      name: spacer
    - component: PageRow
      name: pageRow6
      props:
        justifyContent: start
      children:
        - component: PageColumn
          name: pageColumn1
          layout:
            columnSize: 1
          children:
            - component: Text
              name: text11
              props:
                value: Créer une tache
                variant: h5
              layout:
                columnSize: 1
            - component: Form
              name: form
              children:
                - component: PageColumn
                  name: pageColumn4
                  children:
                    - component: PageRow
                      name: pageRow11
                      props:
                        justifyContent: start
                      children:
                        - component: Text
                          name: text14
                          layout:
                            columnSize: 1
                          props:
                            value: TITRE
                        - component: TextField
                          name: textField
                    - component: PageRow
                      name: pageRow8
                      props:
                        justifyContent: start
                      children:
                        - component: Text
                          name: text15
                          props:
                            value: DESCRIPTION
                        - component: TextField
                          name: textField1
                          layout:
                            columnSize: 1
                    - component: PageRow
                      name: pageRow7
                      props:
                        justifyContent: start
                      children:
                        - component: PageColumn
                          name: pageColumn5
                          layout:
                            columnSize: 1
                          children:
                            - component: Text
                              name: text13
                              layout:
                                columnSize: 1
                            - component: Checkbox
                              name: switch
                              props:
                                mode: switch
                                label: COMPLETÉ
                        - component: DatePicker
                          name: datePicker
                          layout:
                            columnSize: 1
                  layout:
                    columnSize: 1
              props:
                submitButtonText: CRÉER
        - component: Form
          name: form1
          layout:
            columnSize: 1
          children:
            - component: PageColumn
              name: pageColumn3
              children:
                - component: Text
                  name: text12
                  layout:
                    columnSize: 1
                  props:
                    value: Créer Sous tâche
                    variant: h5
                - component: PageRow
                  name: pageRow9
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text17
                      layout:
                        columnSize: 1
                      props:
                        value: TITRE
                    - component: TextField
                      name: textField2
                - component: PageRow
                  name: pageRow10
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text17
                      props:
                        value: ID DE LA TÂCHE
                    - component: Text
                      name: text18
                      props:
                        value:
                          $$jsExpression: gridTache.selection.id
                - component: Checkbox
                  name: switch1
                  props:
                    mode: switch
                    label: COMPLETÉ
                  layout:
                    columnSize: 1
              layout:
                columnSize: 1
          props:
            submitButtonText: CRÉER
  queries:
    - name: listeall
      mode: query
      query:
        kind: rest
        url: https://sw-final-api-2.onrender.com/api/taches/tous
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.api_cle },
            },
          ]
        method: GET
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
    - name: listeSous
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/sous/tous?id=$\
            {parameters.tache_id}`"
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.api_cle },
            },
          ]
        method: GET
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
        - name: tache_id
          value:
            $$jsExpression: gridTache.selection.id
    - name: allListe
      mode: query
      query:
        kind: rest
        url: https://sw-final-api-2.onrender.com/api/taches/tous?complete=true
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.api_cle
        method: GET
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
    - name: supprimerTache
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/supprimer?id=$\
            {parameters.tache_id}`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.api_cle
        method: POST
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
        - name: id
          value:
            $$jsExpression: gridTache.selection.id
    - name: statueSousTache
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/sous/modifierS\
            tatut?id=${parameters.soustache_id}`"
        headers: []
        method: POST
        body:
          kind: raw
          content:
            $$jsExpression: complet = parameters.complet
          contentType: application/json
      parameters:
        - name: soustache_id
          value:
            $$jsExpression: gridSousTache.selection.id
        - name: complet
          value:
            $$jsExpression: gridSousTache.selection.complete
    - name: action
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/supprimer?id=$\
            {parameters.tache_id}`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.cle_api
        method: GET
      parameters:
        - name: cle_api
          value:
            $$env: cleAPI
