# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.55/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - dZd3c7J
  content:
    - component: Text
      name: text
      props:
        value: LISTE ET CRUD DES TÂCHES
        variant: h3
      layout:
        columnSize: 1.681241184767278
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
        gap: 3
      children:
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1.1976400279717458
          children:
            - component: DataGrid
              name: gridTache
              layout:
                columnSize: 1
              props:
                rows:
                  $$jsExpression: "switchFini.checked ? allListe.rows : listeall.rows"
                columns:
                  - field: id
                    type: number
                    width: 50
                  - field: utilisateur_id
                    type: number
                    width: 155
                  - field: titre
                    type: string
                  - field: description
                    type: string
                  - field: date_debut
                    type: dateTime
                  - field: date_echeance
                    type: dateTime
                  - field: complete
                    type: json
                  - field: tache_id
                    type: number
                density: standard
            - component: Checkbox
              name: switchFini
              props:
                mode: switch
                label: Fini
        - component: DataGrid
          name: gridSousTache
          layout:
            columnSize: 0.8023599720282542
            height: 244
          props:
            rows:
              $$jsExpression: listeSous.rows ?? "Séléctionné une tâche!"
            columns:
              - field: id
                type: number
                width: 50
              - field: tache_id
                type: number
              - field: titre
                type: string
                width: 135
              - field: complete
                type: json
            loading: false
    - component: PageRow
      name: pageRow2
      props:
        justifyContent: start
      children:
        - component: Text
          name: text1
          props:
            value: "ID :"
            variant: h6
          layout:
            columnSize: 0.22303943579481667
        - component: Text
          name: text2
          props:
            value:
              $$jsExpression: gridTache.selection.id ?? '1'
          layout:
            columnSize: 0.22303147838498322
        - component: Spacer
          name: spacer1
          layout:
            columnSize: 2.5539290858202
    - component: PageRow
      name: pageRow3
      props:
        justifyContent: start
      children:
        - component: Text
          name: text5
          props:
            value: "CRÉATION:"
            variant: h6
        - component: Text
          name: text3
          props:
            value:
              $$jsExpression: gridTache.selection.date_debut
        - component: Text
          name: text4
          props:
            value: FIN
            variant: h6
        - component: Text
          name: text6
          props:
            value:
              $$jsExpression: gridTache.selection.date_echeance
    - component: PageRow
      name: pageRow1
      props:
        justifyContent: start
      children:
        - component: Text
          name: text7
          props:
            value: "TITRE:"
            variant: h6
          layout:
            columnSize: 0.4899598393574297
        - component: Text
          name: text8
          props:
            value:
              $$jsExpression: gridTache.selection.titre
          layout:
            columnSize: 1.5100401606425704
    - component: PageRow
      name: pageRow5
      props:
        justifyContent: start
      children:
        - component: Text
          name: text9
          props:
            value: "DESCRIPTION:"
            variant: h6
          layout:
            columnSize: 0.4899598393574298
        - component: Text
          name: text10
          props:
            value:
              $$jsExpression: gridTache.selection.description
          layout:
            columnSize: 1.5100401606425702
    - component: PageRow
      name: pageRow4
      props:
        justifyContent: start
      children:
        - component: Button
          name: button
          props:
            content: SUPPRIMER TÂCHE
            onClick:
              $$jsExpressionAction: action.call();listeall.refetch();allListe.refetch()
        - component: Button
          name: button1
          props:
            content: COMPLETER TÂCHE
        - component: Button
          name: button2
          props:
            content: SUPPRIMER          SOUS-TÂCHE
        - component: Button
          name: button3
          props:
            content: COMPLETER SOUS-TÂCHE
            onClick:
              $$jsExpressionAction: statueSousTache.fetch()
    - component: Spacer
      name: spacer
    - component: PageRow
      name: pageRow6
      props:
        justifyContent: start
      children:
        - component: PageColumn
          name: pageColumn1
          layout:
            columnSize: 1
          children:
            - component: Text
              name: text11
              props:
                value: Créer une tache
                variant: h5
              layout:
                columnSize: 1
            - component: Form
              name: form
              children:
                - component: PageColumn
                  name: pageColumn4
                  children:
                    - component: PageRow
                      name: pageRow11
                      props:
                        justifyContent: start
                      children:
                        - component: Text
                          name: text14
                          layout:
                            columnSize: 1
                          props:
                            value: TITRE
                        - component: TextField
                          name: textField4
                    - component: PageRow
                      name: pageRow8
                      props:
                        justifyContent: start
                      children:
                        - component: Text
                          name: text15
                          props:
                            value: DESCRIPTION
                        - component: TextField
                          name: textField5
                          layout:
                            columnSize: 1
                    - component: PageRow
                      name: pageRow7
                      props:
                        justifyContent: start
                      children:
                        - component: PageColumn
                          name: pageColumn5
                          layout:
                            columnSize: 1
                          children:
                            - component: Text
                              name: text13
                              layout:
                                columnSize: 1
                              props:
                                value: FIN
                            - component: Checkbox
                              name: switch
                              props:
                                mode: switch
                                label: COMPLETÉ
                        - component: DatePicker
                          name: datePicker1
                          layout:
                            columnSize: 1
                  layout:
                    columnSize: 1
              props:
                submitButtonText: CRÉER
        - component: Form
          name: form1
          layout:
            columnSize: 1
          children:
            - component: PageColumn
              name: pageColumn3
              children:
                - component: Text
                  name: text12
                  layout:
                    columnSize: 1
                  props:
                    value: Créer Sous tâche
                    variant: h5
                - component: PageRow
                  name: pageRow9
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text17
                      layout:
                        columnSize: 1
                      props:
                        value: TITRE
                    - component: TextField
                      name: textField2
                - component: PageRow
                  name: pageRow10
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text16
                      props:
                        value: ID DE LA TÂCHE
                    - component: Text
                      name: text24
                      props:
                        value:
                          $$jsExpression: gridTache.selection.id
                - component: Checkbox
                  name: switch1
                  props:
                    mode: switch
                    label: COMPLETÉ
                  layout:
                    columnSize: 1
              layout:
                columnSize: 1
          props:
            submitButtonText: CRÉER
    - component: Spacer
      name: spacer2
    - component: PageRow
      name: pageRow13
      props:
        justifyContent: start
      children:
        - component: Text
          name: text18
          props:
            value: Modifier tâche
            variant: h5
        - component: Text
          name: text19
          props:
            value: Modifier Sous tâche
            variant: h5
    - component: PageRow
      name: pageRow12
      props:
        justifyContent: start
      children:
        - component: Form
          name: form2
          children:
            - component: PageRow
              name: pageRow15
              props:
                justifyContent: start
              children:
                - component: PageColumn
                  name: pageColumn7
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text23
                      layout:
                        columnSize: 1
                      props:
                        value: ID DE LA TÂCHE
                    - component: Text
                      name: text25
                      layout:
                        columnSize: 1
                      props:
                        value: TITRE
                    - component: Text
                      name: text26
                      props:
                        value: DESCRIPTION
                    - component: Text
                      name: text27
                      layout:
                        columnSize: 1
                      props:
                        value: FIN
                    - component: Checkbox
                      name: switch3
                      props:
                        mode: switch
                        label: COMPLETÉ
                - component: PageColumn
                  name: pageColumn8
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text21
                      layout:
                        columnSize: 1
                      props:
                        value:
                          $$jsExpression: gridTache.selection.id
                    - component: TextField
                      name: textField
                    - component: TextField
                      name: textField1
                      layout:
                        columnSize: 1
                    - component: DatePicker
                      name: datePicker
                      layout:
                        columnSize: 1
                    - component: Spacer
                      name: spacer3
        - component: Form
          name: form3
          children:
            - component: PageRow
              name: pageRow14
              props:
                justifyContent: start
              children:
                - component: PageColumn
                  name: pageColumn2
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text20
                      layout:
                        columnSize: 1
                      props:
                        value: ID DE LA SOUS-TÂCHE
                    - component: Text
                      name: text22
                      layout:
                        columnSize: 1
                      props:
                        value: TITRE
                    - component: Checkbox
                      name: switch2
                      layout:
                        columnSize: 1
                      props:
                        mode: switch
                        label: COMPLETÉ
                - component: PageColumn
                  name: pageColumn6
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text28
                      layout:
                        columnSize: 1
                      props:
                        value:
                          $$jsExpression: gridSousTache.selection.id
                    - component: TextField
                      name: textField3
  queries:
    - name: listeall
      mode: query
      query:
        kind: rest
        url: https://sw-final-api-2.onrender.com/api/taches/tous
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.api_cle },
            },
          ]
        method: GET
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
    - name: listeSous
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/sous/tous?id=$\
            {parameters.tache_id}`"
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.api_cle },
            },
          ]
        method: GET
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
        - name: tache_id
          value:
            $$jsExpression: gridTache.selection.id ?? 'akita'
    - name: allListe
      mode: query
      query:
        kind: rest
        url: https://sw-final-api-2.onrender.com/api/taches/tous?complete=true
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.api_cle
        method: GET
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
    - name: supprimerTache
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/supprimer?id=$\
            {parameters.tache_id}`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.api_cle
        method: POST
        searchParams: []
      parameters:
        - name: api_cle
          value:
            $$env: cleAPI
        - name: id
          value:
            $$jsExpression: gridTache.selection.id
    - name: supprimeSousTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/supprimer?id=$\
            {parameters.tache_id}`"
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.cle_api },
            },
          ]
        method: POST
        searchParams: []
      parameters:
        - name: cle_api
          value:
            $$env: cleAPI
        - name: tache_id
          value:
            $$jsExpression: gridTache.selection.id
    - name: action
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`https://sw-final-api-2.onrender.com/api/taches/sous/modifierS\
            tatut?id=${parameters.soustache_id}`"
        headers: []
        method: POST
        body:
          kind: raw
          content:
            $$jsExpression: "`{\r

              \  \"complet\": ${parameters.complete} \r

              }`"
          contentType: text/plain
      parameters:
        - name: complet
          value:
            $$jsExpression: gridSousTache.selection.complet
        - name: cle_api
          value:
            $$env: cleAPI
